# Generated by Django 4.1.6 on 2023-04-12 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodotto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contattacci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('oggetto', models.CharField(max_length=100)),
                ('messaggio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rimborsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('prodotto', models.CharField(max_length=100)),
                ('prod_id', models.IntegerField()),
                ('prezzo', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('motivo', models.TextField(max_length=2000)),
                ('effettuato', models.DateTimeField(auto_now_add=True)),
                ('rimborsato', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-effettuato',),
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commento', models.TextField(max_length=250)),
                ('valutazione', models.IntegerField(blank=True, default=0, null=True)),
                ('creata', models.DateTimeField(auto_now_add=True)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotto.prodotto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('prodotto', models.CharField(max_length=100)),
                ('prod_id', models.IntegerField()),
                ('prezzo', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('totale', models.FloatField()),
                ('indirizzo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('spedito', models.BooleanField(default=False)),
                ('restituito', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
    ]
