# Generated by Django 4.0 on 2023-09-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodotto', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contattaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('oggetto', models.CharField(max_length=100)),
                ('messaggio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totale', models.FloatField()),
                ('indirizzo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('spedito', models.BooleanField(default=False)),
                ('restituito', models.BooleanField(default=False)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prodotto.prodotto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
        migrations.CreateModel(
            name='Rimborsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('motivo', models.TextField(max_length=2000)),
                ('effettuato', models.DateTimeField(auto_now_add=True)),
                ('rimborsato', models.BooleanField(default=False)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ordine.ordine')),
            ],
            options={
                'ordering': ('-effettuato',),
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commento', models.TextField(max_length=250)),
                ('valutazione', models.IntegerField(blank=True, default=0, null=True)),
                ('creata', models.DateTimeField(auto_now_add=True)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotto.prodotto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
